"""
This type stub file was generated by pyright.
"""

import io
from typing import Sequence
from importlib.metadata import EntryPoint
from importlib_metadata import EntryPoint

is_posix = ...
py311 = ...
py39 = ...
py38 = ...
class EncodedIO(io.TextIOWrapper):
    def close(self) -> None:
        ...
    


if py39:
    ...
else:
    ...
def importlib_metadata_get(group: str) -> Sequence[EntryPoint]:
    ...

def formatannotation_fwdref(annotation, base_module=...): # -> str:
    """vendored from python 3.7"""
    ...

