"""
This type stub file was generated by pyright.
"""

import sys
import werkzeug.exceptions as exceptions
from .apis import AbstractAPI
from .apps import AbstractApp
from .decorators.produces import NoContent
from .exceptions import ProblemException
from .operations import compat
from .problem import problem
from .resolver import Resolution, Resolver, RestyResolver
from .utils import not_installed_error
from flask import request
from .apis.flask_api import FlaskApi, context
from .apps.flask_app import FlaskApp
from .apis.aiohttp_api import AioHttpApi
from .apps.aiohttp_app import AioHttpApp

"""
Connexion is a framework that automagically handles HTTP requests based on OpenAPI Specification
(formerly known as Swagger Spec) of your API described in YAML format. Connexion allows you to
write an OpenAPI specification, then maps the endpoints to your Python functions; this makes it
unique, as many tools generate the specification based on your Python code. You can describe your
REST API in as much detail as you want; then Connexion guarantees that it will work as you
specified.
"""
full_name = ...
App = ...
Api = ...
__version__ = ...
