"""
This type stub file was generated by pyright.
"""

import typing as t
import yaml

"""
Module containing all code related to json schema validation.
"""
class ExtendedSafeLoader(yaml.SafeLoader):
    """Extends the yaml SafeLoader to coerce all keys to string so the result is valid json."""
    def __init__(self, stream) -> None:
        ...
    
    def extended_construct_mapping(self, node, deep=...): # -> dict[str, Any]:
        ...
    


class FileHandler:
    """Handler to resolve file refs."""
    def __call__(self, uri): # -> Any:
        ...
    


class URLHandler:
    """Handler to resolve url refs."""
    def __call__(self, uri): # -> Any:
        ...
    


default_handlers = ...
def resolve_refs(spec, store=..., handlers=...): # -> Mapping[Unknown, Unknown] | Incomplete | list[Unknown] | tuple[Unknown, ...]:
    """
    Resolve JSON references like {"$ref": <some URI>} in a spec.
    Optionally takes a store, which is a mapping from reference URLs to a
    dereferenced objects. Prepopulating the store can avoid network calls.
    """
    ...

def allow_nullable(validation_fn: t.Callable) -> t.Callable:
    """Extend an existing validation function, so it allows nullable values to be null."""
    ...

def validate_required(validator, required, instance, schema): # -> Generator[ValidationError, Any, None]:
    ...

def validate_readOnly(validator, ro, instance, schema): # -> Generator[ValidationError, Any, None]:
    ...

def validate_writeOnly(validator, wo, instance, schema): # -> Generator[ValidationError, Any, None]:
    ...

NullableTypeValidator = ...
NullableEnumValidator = ...
Draft4RequestValidator = ...
Draft4ResponseValidator = ...
