"""
This type stub file was generated by pyright.
"""

"""
This module defines interfaces for requests and responses used in Connexion for authentication,
validation, serialization, etc.
"""
class ConnexionRequest:
    """Connexion interface for a request."""
    def __init__(self, url, method, path_params=..., query=..., headers=..., form=..., body=..., json_getter=..., files=..., context=..., cookies=...) -> None:
        ...
    
    @property
    def json(self):
        ...
    


class ConnexionResponse:
    """Connexion interface for a response."""
    def __init__(self, status_code=..., mimetype=..., content_type=..., body=..., headers=..., is_streamed=...) -> None:
        ...
    


