info:
  title: Test Application
  version: 3.0.3
openapi: 3.0.3
paths:
  /:
    get:
      description: Say "Hello, World!"
      operationId: root.get
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Said "Hello, World!" successfully
