"""
This type stub file was generated by pyright.
"""

"""
This module defines utility functions related to the Flask framework.
"""
PATH_PARAMETER = ...
PATH_PARAMETER_CONVERTERS = ...
def flaskify_endpoint(identifier, randomize=...): # -> str:
    """
    Converts the provided identifier in a valid flask endpoint name

    :type identifier: str
    :param randomize: If specified, add this many random characters (upper case
        and digits) to the endpoint name, separated by a pipe character.
    :type randomize: int | None
    :rtype: str

    """
    ...

def convert_path_parameter(match, types): # -> str:
    ...

def flaskify_path(swagger_path, types=...): # -> str:
    """
    Convert swagger path templates to flask path templates

    :type swagger_path: str
    :type types: dict
    :rtype: str

    >>> flaskify_path('/foo-bar/{my-param}')
    '/foo-bar/<my_param>'

    >>> flaskify_path('/foo/{someint}', {'someint': 'int'})
    '/foo/<int:someint>'
    """
    ...

def is_flask_response(obj: object) -> bool:
    """
    Verifies if obj is a default Flask response instance.

    >>> is_flask_response(redirect('http://example.com/'))
    True
    >>> is_flask_response(flask.Response())
    True
    """
    ...

