"""
This type stub file was generated by pyright.
"""

from typing import Callable

REVISION_SCRIPT_TOKEN = ...
_registry: dict = ...
def register(name: str) -> Callable:
    """A function decorator that will register that function as a write hook.

    See the documentation linked below for an example.

    .. versionadded:: 1.2.0

    .. seealso::

        :ref:`post_write_hooks_custom`


    """
    ...

@register("console_scripts")
def console_scripts(path: str, options: dict, ignore_output: bool = ...) -> None:
    ...

