"""
This type stub file was generated by pyright.
"""

import copy

class UserInfo:
    """Read only interface to a user info store"""
    def __init__(self) -> None:
        ...
    
    def __call__(self, **kwargs): # -> None:
        ...
    


class UserInfoDB(UserInfo):
    """Read only interface to a user info store"""
    def __init__(self, db=...) -> None:
        ...
    
    @staticmethod
    def filter(userinfo, user_info_claims=...): # -> dict[Any, Any]:
        """
        Return only those claims that are asked for.
        It's a best effort task; if essential claims are not present
        no error is flagged.

        :param userinfo: A dictionary containing the available user info.
        :param user_info_claims: A dictionary specifying the asked for claims
        :return: A dictionary of filtered claims.
        """
        ...
    
    def __call__(self, userid, user_info_claims=..., **kwargs): # -> dict[Any, Any]:
        ...
    


