"""
This type stub file was generated by pyright.
"""

import abc
from .security_handler_factory import AbstractSecurityHandlerFactory

"""
This module defines an abstract asynchronous SecurityHandlerFactory which supports the creation of
asynchronous security handlers for coroutine operations.
"""
logger = ...
class AbstractAsyncSecurityHandlerFactory(AbstractSecurityHandlerFactory):
    def check_oauth_func(self, token_info_func, scope_validate_func): # -> (request: Unknown, token: Unknown, required_scopes: Unknown) -> Coroutine[Any, Any, object | Unknown | Any]:
        ...
    
    @classmethod
    def verify_security(cls, auth_funcs, function): # -> _Wrapped[..., Unknown, (request: Unknown), Coroutine[Any, Any, Unknown]]:
        ...
    
    @abc.abstractmethod
    def get_token_info_remote(self, token_info_url): # -> None:
        """
        Return a function which will call `token_info_url` to retrieve token info.

        Returned function must accept oauth token in parameter.
        It must return a token_info dict in case of success, None otherwise.

        :param token_info_url: Url to get information about the token
        :type token_info_url: str
        :rtype: types.FunctionType
        """
        ...
    


