"""
This type stub file was generated by pyright.
"""

from saml2.entity import Entity

__author__ = ...
IDPDISC_POLICY = ...
class DiscoveryServer(Entity):
    def __init__(self, config=..., config_file=...) -> None:
        ...
    
    def parse_discovery_service_request(self, url=..., query=...): # -> dict[str, list[str]]:
        ...
    
    @staticmethod
    def create_discovery_service_response(return_url=..., returnIDParam=..., entity_id=..., **kwargs): # -> str:
        ...
    
    def verify_sp_in_metadata(self, entity_id): # -> bool:
        ...
    
    def verify_return(self, entity_id, return_url): # -> bool:
        ...
    


