"""
This type stub file was generated by pyright.
"""

from saml2.server import Server

"""
Contains classes used in the SAML ECP profile
"""
logger = ...
def ecp_capable(headers): # -> bool:
    ...

def ecp_auth_request(cls, entityid=..., relay_state=..., sign=..., sign_alg=..., digest_alg=...): # -> tuple[Any, str]:
    """Makes an authentication request.

    :param entityid: The entity ID of the IdP to send the request to
    :param relay_state: To where the user should be returned after
        successfull log in.
    :param sign: Whether the request should be signed or not.
    :return: AuthnRequest response
    """
    ...

def handle_ecp_authn_response(cls, soap_message, outstanding=...): # -> tuple[AuthnResponse, Any | None]:
    ...

def ecp_response(target_url, response): # -> str:
    ...

class ECPServer(Server):
    """This deals with what the IdP has to do

    TODO: Still tentative
    """
    def __init__(self, config_file=..., config=..., cache=...) -> None:
        ...
    
    def parse_ecp_authn_query(self): # -> None:
        ...
    
    def ecp_response(self): # -> str:
        ...
    


