"""
This type stub file was generated by pyright.
"""

logger = ...
class Eptid:
    def __init__(self, secret) -> None:
        ...
    
    def make(self, idp, sp, args):
        ...
    
    def __getitem__(self, key):
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def get(self, idp, sp, *args):
        ...
    
    def close(self): # -> None:
        ...
    


class EptidShelve(Eptid):
    def __init__(self, secret, filename) -> None:
        ...
    
    def close(self): # -> None:
        ...
    


