"""
This type stub file was generated by pyright.
"""

__author__ = ...
class Filter:
    def __init__(self) -> None:
        ...
    
    def __call__(self, *args, **kwargs): # -> None:
        ...
    


class AllowDescriptor(Filter):
    def __init__(self, allow) -> None:
        """

        :param allow: List of allowed descriptors
        :return:
        """
        ...
    
    def __call__(self, entity_descriptor): # -> None:
        ...
    


