"""
This type stub file was generated by pyright.
"""

from .abstract import AbstractApp

"""
This module defines an AioHttpApp, a Connexion application to wrap an AioHttp application.
"""
logger = ...
class AioHttpApp(AbstractApp):
    def __init__(self, import_name, only_one_api=..., **kwargs) -> None:
        ...
    
    def create_app(self):
        ...
    
    def get_root_path(self): # -> Path:
        ...
    
    def set_errors_handlers(self): # -> None:
        ...
    
    def add_api(self, specification, **kwargs):
        ...
    
    def run(self, port=..., server=..., debug=..., host=..., **options): # -> None:
        ...
    


