"""
This type stub file was generated by pyright.
"""

import io
import os
import importlib_resources
import importlib_metadata
from configparser import ConfigParser
from typing import Any, List, Optional, Sequence, Union
from importlib.metadata import EntryPoint as EntryPoint
from importlib_metadata import EntryPoint

if True:
    ...
is_posix = ...
py311 = ...
py310 = ...
py39 = ...
class EncodedIO(io.TextIOWrapper):
    def close(self) -> None:
        ...
    


if py39:
    importlib_resources = ...
    importlib_metadata = ...
else:
    ...
def importlib_metadata_get(group: str) -> Sequence[EntryPoint]:
    ...

def formatannotation_fwdref(annotation: Any, base_module: Optional[Any] = ...) -> str:
    """vendored from python 3.7"""
    ...

def read_config_parser(file_config: ConfigParser, file_argument: Sequence[Union[str, os.PathLike[str]]]) -> List[str]:
    ...

